name: DistributedComputing
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=8.0.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - bleach=4.1.0
  - boost-cpp=1.73.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.6.0
  - grpc-cpp=1.46.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - iniconfig=1.1.1
  - ipykernel=6.15.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.3
  - jupyter_core=4.11.1
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.15.2
  - jupyterlab_widgets=1.0.0
  - krb5=1.19.3
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.0
  - libcurl=7.84.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm12=12.0.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.4
  - openjdk=11.0.9.1
  - openssl=1.1.1q
  - orc=1.7.4
  - packaging=21.3
  - pandas=1.5.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py4j=0.10.9.5
  - pyarrow=8.0.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pyspark=3.3.0
  - pytest=7.1.2
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.5
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.1.2
  - requests=2.28.1
  - send2trash=1.8.0
  - setuptools=63.4.1
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.3
  - stack_data=0.2.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022e
  - urllib3=1.26.12
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.6
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - pyqt5-sip==12.11.0
prefix: /opt/anaconda3/envs/DistributedComputing
